#!/bin/bash

PROJECT_ROOT_PATH="$(cd $(dirname "$0")/../ ; pwd)"
PROJECT_GIT_DIR_PATH="${PROJECT_ROOT_PATH}/.git"
PROJECT_DIR_NAME="$(basename ${PROJECT_ROOT_PATH})"

# if there is a .git directory at the project root then rely on git for the version string
if [ -r "${PROJECT_GIT_DIR_PATH}" ] ; then
    git describe --tags --abbrev --dirty --always 2>/dev/null
    if [ $? -eq 0 ]; then
        exit 0
    fi
fi

# if the proejct root directory matches the naming convetion of an extracted archive then
# get the version number out of that
if [[ "${PROJECT_DIR_NAME}" =~ ^(RTLSDR-Airband|Boondock-Airband)-[0-9]*\.[0-9]*\.[0-9]*$ ]]; then
    echo ${PROJECT_DIR_NAME} | cut -d '-' -f 3
    exit 0
fi

# fallback: use a default version if git is not available or directory name doesn't match
echo "0.0.0-unknown"
exit 0
